[project]
name = "service"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
  "alembic>=1.20.0",
  "alembic-postgresql-enum>=1.10.0",
  "fastapi>=0.141.1",
  "psycopg2-binary>=2.9.13",
  "pydantic>=2.13.5",
  "pydantic-settings>=2.15.0",
  "sqlalchemy>=2.0.54",
  "uvicorn>=0.53.0",
]

[tool.alembic]
script_location = "%(here)s/src/db/migrations"
file_template = "%%(year)d%%(month).2d%%(day).2d%%(hour).2d%%(minute).2d-%%(slug)s-%%(rev)s"
prepend_sys_path = ["."]
truncate_slug_length = 30

[[tool.alembic.post_write_hooks]]
name = "ruff"
type = "exec"
executable = "ruff"
options = "format REVISION_SCRIPT_FILENAME"
