"""Add payments.webhook_sent.

Revision ID: d25426c4b629
Revises: e67710615061
Create Date: 2026-09-18 02:11:15.633908

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d25426c4b629"
down_revision: str | Sequence[str] | None = "e67710615061"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "payments",
        sa.Column("webhook_sent_at", sa.DateTime(timezone=True), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("payments", "webhook_sent_at")
    # ### end Alembic commands ###
