"""Add outbox_messages missing fields.

Revision ID: 2c9ee9ac8b22
Revises: 931cb6eca8b8
Create Date: 2026-09-17 17:28:34.770421

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2c9ee9ac8b22"
down_revision: str | Sequence[str] | None = "931cb6eca8b8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "outbox_messages",
        sa.Column("publish_attempts", sa.BigInteger(), nullable=False),
    )
    op.create_index(
        op.f("ix_outbox_messages_next_attempt_at"),
        "outbox_messages",
        ["next_attempt_at"],
        unique=False,
    )
    op.drop_column("outbox_messages", "attempts")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "outbox_messages",
        sa.Column("attempts", sa.BIGINT(), autoincrement=False, nullable=False),
    )
    op.drop_index(
        op.f("ix_outbox_messages_next_attempt_at"), table_name="outbox_messages"
    )
    op.drop_column("outbox_messages", "publish_attempts")
    # ### end Alembic commands ###
